debugging pipeline

diff --git a/.github/workflows/terraform-cd.yml b/.github/workflows/terraform-cd.yml
--- a/.github/workflows/terraform-cd.yml
+++ b/.github/workflows/terraform-cd.yml
@@ -44,6 +44,20 @@ jobs:
           name: terraform-plan
           path: artifacts
 
+      # Check if artifact exists after download
+      - name: Verify artifact location
+        run: |
+          ls -l artifacts
+ 
+      # Check if the tfplan file exists
+      - name: Check tfplan file existence
+        run: |
+          if [ ! -f artifacts/tfplan.out ]; then
+            echo "tfplan.out not found!";
+            exit 1;
+          else
+            echo "tfplan.out found!";
+          fi
 
       
       - name: List files
